<?php

namespace php;

use Brain\Monkey\Expectation\Exception\ExpectationArgsRequired;
use Mockery;
use PluginTestCase\PluginTestCase;
use VolunteerManager\Api;
use Brain\Monkey\Functions;
use VolunteerManager\Employee\IEmployeeApiValidator;

class ApiTest extends PluginTestCase
{
    private $api;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->api = new Api();
    }

    /**
     * @throws ExpectationArgsRequired
     */
    public function testRegisterPostEndpoint()
    {
        $endpoint = '/test-endpoint/';
        $callback = function () {
            return 'Test callback';
        };
        $validator = Mockery::mock(IEmployeeApiValidator::class);
        $namespace = 'volunteer-manager/v1';

        Functions\expect('register_rest_route')
            ->once()
            ->with(
                $namespace,
                $endpoint,
                Mockery::on(function ($arg) use ($callback) {
                    return $arg['methods'] === 'POST'
                        && is_callable($arg['callback'])
                        && $arg['callback']() === $callback()
                        && is_callable($arg['permission_callback']);
                })
            );

        $this->api->registerPostEndpoint($endpoint, $callback, $validator, $namespace);
    }
}
